### ISSUE TITLE
[build] Upgrade to Webpack 4

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#161]
Using component framework like element-ui requires upgrade to Webpack 4.

- [x] not using VUE CLI -- using webpack 4  ( vue cli isn't great for a legacy php app )
- [x] use bundles ( root / study / review )
- [x] configure file-loader to remove the hashes
- [x] enable Extract CSS, *extract CSS per bundle*
- [x] import the legacy stylesheets in the webpack bundles, se we can just use `webpack --watch`
- [x] refactor symfony's assets handling to include the css/js bundles

**Comment by fabd** [comment]
Still to do:

[_] phase out "build_app.php" and use `[chunkhash]` in output filenames? (how does Symfony know the hashes though? This means I would still use `build_app.php` to create a map of filenames & hashes, but instead of generating my own hash from filemtime, we could use the better `chunkhash` based on chunk contents from Webpack -- the minor benefit being that some chinks like vendors chunk would not be reloaded by client after some production updates -- either way... it's better).

**Comment by fabd** [comment]
Things ruled out:

- Deploying ES5 & ES2015. [Deploying ES2015+ Code in Production Today](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) Not very difficult to setup however creates a bunch more chunks, and the file size differences is really small. Eg. in one test Vendors chunk with Vue+element+FontAwesome goes from ~195 kb to ~185 kb. Most chunks become just barely 1kb smaller. I don't think it's worth making a more complex webpack config.

**Comment by fabd** [comment]
This is more or less done, summary of recent updates:

- enabled `ts-loader`, TypeScript files should go into `src/lib/front/vue/`
- Vue files should use `lang="ts"`
- custom types should go in `lib/front/vue/types/` (eg. globals.d.ts declares `window.App` which is set by legacy javascript to interface with the Vue code, such as manually instancing a Vue component)
- API is not great, just translating old code to TS, should be refactored to async/ await and a less verbose interface
- **bundles**: in order to solve issue with multiple Vue instances the bundles were simplified, there is no more "root" bundle dependency, only the webpack "vendor" or "common" bundle, plus "study"/"review"/etc.
- **"vendors" chunk** is enabled in dev build (npm run dev) : with webpack watch mode (npm run watch), it doesn't need to recompile the vendors bundle, so it's fairly fast and the other dev bundles are smaller (commons chunk is a tad smaller, and could potentially be used in production, but would change more often)
- **extracted css bundles in dev** : the css injected by javascript is slow, and causes visual glitches when refreshing the page

## TODO?

- could use Babel with TypeScript for faster compilation and better browser targeting. Currently TS files are compiled by ts-loader, tsconfig should output ES5 but not necessarily IE11+ compatible code which browserslist could account for

## Using Vue with TypeScript

- JSDoc : I didn't mind if it's verbose, to be able to write plain Javascript, but the typechecking is very inconsistent, and nearly unusable in Vue files

- `vue-class-component` : is kind of a hack, and already deprecated for Vue 3, also headaches setting up decorator support with Babel & TS. Plus, added complexity should someone want to contribute a little fix, the plain Vue syntax is much easier to understand

Finally, after some digging up, **Vue + types** works relatively well and live typechecking in VSCode works reliably.

## Vue + TYPES gotchas

Always **specify the return type for getters**.

For the basic Vue component options typechecks, **use Vue.extend()**:

    export default Vue.extend({ ... })

To type an **Array prop** (also note how `default` uses an _arrow function_):

    items: {
      type: Array as () => DictListEntry[],
      default: () => [],
    },

To type an **Object prop**:

    someProp: {
      type: Object as () => MyObjectInterface,
