### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#54]
Refactoring (php templates + oldschool JS) to VueJS components & phasing out YUI 2

- [ ] Refactor the Flashcard Review page as a VueJS component #38
- [ ] Refactor SharedStories list as a VueJS component #21
- [ ] Refactor the Study search auto-complete #9

For phasing out YUI 2

- [ ] VueJS modal that can replace the Edit Keyword / Edit Story / Edit Flashcard dialogs

Improve the webpack build

- [ ] add ESLint
  - [ ] also lint `.vue` files
- [ ] convert the old `batch/build.sh` script to webpack

Javascript trivia

- [ ] find a good assert() system that doesn't get compiled in the production build
- [ ] find a good way to remove all console.log / warn / error() from the production build

**Comment by Erlemar** [comment]
I have a little suggestion about open sourcing: I have found a [thread ](https://www.reddit.com/r/learnprogramming/comments/5wgefy/many_devs_here_on_reddit_and_on_slack_were_asking/)on reddit, where people can volonteer to contribute to open source project. Every weekend they receive a newsletter with the list of the projects, So if you feel like trying, you could [suggest](https://devchat.devolio.net/hellocode/suggest/) kanji-koohii as a project; some peole should be able to help.

**Comment by fabd** [comment]
Thank you Erlemar. That is an interesting option I didn't think about.
